<?php
include_once 'base/BasePages.php';
/**
 * Pages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Pages extends BasePages
{
    public static function instance()
    {
            static $_instances;
            if (empty($_instances))
            {
                $_instances = new Pages();
            }

            return $_instances;
    }
    
    public function findByPath($directory = null, $controller = null, $action = null)
    {
        $q = Doctrine_Query::create()->from('Pages p');
        $q->where('1=?', 1);
        if(!is_null($controller)){
            $q->andWhere('p.controller = ?', "$controller");
        }
        if(!is_null($directory)) {
            $q->andWhere('p.directory = ?', "$directory");
        }
        if(!is_null($action)){
            $q->andWhere('p.action = ?', "$action");
        }
        return $q->execute()->getFirst();
    }

    public function loadAll(){
        return Doctrine_Core::getTable('Pages')->findAll();
    }
}