Pages:
  connection: default
  tableName: Pages
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    title:
      type: string(32)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    menu:
      type: string(32)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    directory:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    controller:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    action:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    role_allowed:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      default: admin
      notnull: false
      autoincrement: false
    user_allowed:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    published:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: false
      autoincrement: false
    parent:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
Roles:
  connection: default
  tableName: Roles
  columns:
    id:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(32)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Users2Roles:
      local: id
      foreign: role_id
      type: many
Users:
  connection: default
  tableName: Users
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    username:
      type: string(128)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    password:
      type: string(128)
      fixed: true
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email:
      type: string(254)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    last_login:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: false
      autoincrement: false
    active:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: false
      autoincrement: false
  relations:
    Users2Roles:
      local: id
      foreign: user_id
      type: many
    Worktimes:
      local: id
      foreign: user_id
      type: many
Users2Roles:
  connection: default
  tableName: Users2Roles
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    user_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: false
      autoincrement: false
    role_id:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Roles:
      local: role_id
      foreign: id
      type: one
    Users:
      local: user_id
      foreign: id
      type: one
Worktimes:
  connection: default
  tableName: Worktimes
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    work_date:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      default: '0000-00-00'
      notnull: true
      autoincrement: false
    time_start:
      type: time(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    time_stop:
      type: time(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    user_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: true
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      default: '0000-00-00 00:00:00'
      notnull: true
      autoincrement: false
    updated_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Users:
      local: user_id
      foreign: id
      type: one
